# Generated by Django 4.1.2 on 2023-11-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('part_disctiption', models.TextField(max_length=800)),
                ('part_image_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('part_image_a', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('part_image_b', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('part_image_c', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('part_image_d', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('part_customer', models.CharField(max_length=150)),
                ('part_type', models.CharField(choices=[('penu', 'پنوماتیکی'), ('hydro', 'هیدرولیکی'), ('valves', 'شیرآلات صنعتی')], max_length=100)),
                ('part_catalog', models.FileField(upload_to='documents/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'قطعات',
                'verbose_name_plural': 'قطعات',
            },
        ),
    ]
