# Generated by Django 4.2.5 on 2023-11-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('part_disctiption', models.TextField(max_length=200)),
                ('part_image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('part_customer', models.CharField(max_length=100)),
                ('part_type', models.CharField(choices=[{'hydro': 'هیدرولیکی', 'penu': 'پنوماتیکی'}])),
            ],
            options={
                'verbose_name': 'قطعات',
                'verbose_name_plural': 'قطعات',
            },
        ),
    ]
