# Generated by Django 4.2.5 on 2023-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('penu', 'پنوماتیکی'), ('hydro', 'هیدرولیکی'), ('valves', 'شیرآلات صنعتی')]),
        ),
    ]
