# Generated by Django 4.2.5 on 2023-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_part_part_image_alter_part_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_customer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_disctiption',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=100),
        ),
    ]
