# Generated by Django 4.2.5 on 2023-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_part_part_customer_alter_part_part_disctiption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_image',
            new_name='part_image_a',
        ),
        migrations.AddField(
            model_name='part',
            name='part_image_b',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='part_image_c',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='part_image_d',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='part_image_main',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
