# Generated by Django 4.2.5 on 2023-11-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_part_image_part_part_image_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_catalog',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
