# Generated by Django 4.2.5 on 2023-11-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiandishan', '0002_services_testimonials_alter_about_us_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='serv_img',
        ),
        migrations.AddField(
            model_name='services',
            name='serv_description',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
