# Generated by Django 4.2.5 on 2023-11-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiandishan', '0004_overview_about_us_about_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='serv_img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
