# Generated by Django 4.2.5 on 2023-11-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atiandishan', '0005_services_serv_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='part',
        ),
    ]
