# Generated by Django 4.2.5 on 2023-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiandishan', '0006_delete_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='about_long_description',
            field=models.TextField(max_length=1500),
        ),
    ]
