# Generated by Django 4.2.5 on 2023-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiandishan', '0007_alter_about_us_about_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='cer_qty_description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='overview',
            name='customer_qty_description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='overview',
            name='expr_year_description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='overview',
            name='project_qty_description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='services',
            name='serv_description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='cert_description',
            field=models.TextField(max_length=1500),
        ),
    ]
