# Generated by Django 4.2.5 on 2023-11-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atiandishan', '0009_alter_services_serv_img_alter_testimonials_cert_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='serv_description',
        ),
    ]
