# Generated by Django 4.1.2 on 2023-11-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiandishan', '0010_remove_services_serv_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='serv_img',
            new_name='serv_img1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serv_name',
        ),
        migrations.AddField(
            model_name='services',
            name='serv_img2',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='serv_img3',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='serv_img4',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
