# Generated by Django 4.1.2 on 2023-12-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(max_length=1000, verbose_name='متن اصلی خبر')),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='عکس خبر')),
            ],
        ),
    ]
